// Visualizar el nombre y salario de los empleados de los que el número de empleado es impar (PISTA: MOD)
SELECT EMPLOYEE_ID AS "ID Empleado", FIRST_NAME AS "Nombre", SALARY AS "Salario" FROM EMPLOYEES WHERE MOD(EMPLOYEE_ID,2)<>0 ORDER BY EMPLOYEE_ID;

// Prueba con los siguientes valores aplicando las funciones TRUNC y ROUND, con 1 y 2 decimales.
-- 25.67,0
SELECT ROUND(25.67,0) AS PRUEBA FROM DUAL;
SELECT TRUNC(25.67,0) AS PRUEBA FROM DUAL;

-- 25.67,1
SELECT ROUND(25.67,1) AS PRUEBA FROM DUAL;
SELECT TRUNC(25.67,1) AS PRUEBA FROM DUAL;

-- 25.34,1
SELECT ROUND(25.34,1) AS PRUEBA FROM DUAL;
SELECT TRUNC(25.34,1) AS PRUEBA FROM DUAL;

-- 25.34,2
SELECT ROUND(25.34,2) AS PRUEBA FROM DUAL;
SELECT TRUNC(25.34,2) AS PRUEBA FROM DUAL;

-- 25.67,-1
SELECT ROUND(25.67,-1) AS PRUEBA FROM DUAL;
SELECT TRUNC(25.67,-1) AS PRUEBA FROM DUAL;
