// Probar los 4 operadores de conjunto: UNION, UNION ALL, INTSERSCT, MINUS

SELECT CODIGO, NOMBRE FROM COCHES1
UNION
SELECT CODE, NAME FROM COCHES2;

SELECT CODIGO, NOMBRE FROM COCHES1
UNION ALL
SELECT CODE, NAME FROM COCHES2;

SELECT CODIGO, NOMBRE FROM COCHES1
INTERSECT
SELECT CODE, NAME FROM COCHES2;

SELECT CODIGO, NOMBRE FROM COCHES1
MINUS
SELECT CODE, NAME FROM COCHES2;

SELECT CODE, NAME FROM COCHES2
MINUS
SELECT CODIGO, NOMBRE FROM COCHES1;